#pragma once
#include <tgbotxx/Api.hpp>
#include <tgbotxx/Bot.hpp>
#include <tgbotxx/Exception.hpp>

/// Objects
#include <tgbotxx/objects/AcceptedGiftTypes.hpp>
#include <tgbotxx/objects/AffiliateInfo.hpp>
#include <tgbotxx/objects/Animation.hpp>
#include <tgbotxx/objects/Audio.hpp>
#include <tgbotxx/objects/BackgroundFill.hpp>
#include <tgbotxx/objects/BackgroundType.hpp>
#include <tgbotxx/objects/Birthdate.hpp>
#include <tgbotxx/objects/BotCommand.hpp>
#include <tgbotxx/objects/BotCommandScope.hpp>
#include <tgbotxx/objects/BotDescription.hpp>
#include <tgbotxx/objects/BotName.hpp>
#include <tgbotxx/objects/BotShortDescription.hpp>
#include <tgbotxx/objects/BusinessBotRights.hpp>
#include <tgbotxx/objects/BusinessConnection.hpp>
#include <tgbotxx/objects/BusinessIntro.hpp>
#include <tgbotxx/objects/BusinessLocation.hpp>
#include <tgbotxx/objects/BusinessMessagesDeleted.hpp>
#include <tgbotxx/objects/BusinessOpeningHours.hpp>
#include <tgbotxx/objects/BusinessOpeningHoursInterval.hpp>
#include <tgbotxx/objects/CallbackGame.hpp>
#include <tgbotxx/objects/CallbackQuery.hpp>
#include <tgbotxx/objects/ChatAdministratorRights.hpp>
#include <tgbotxx/objects/ChatBackground.hpp>
#include <tgbotxx/objects/ChatBoostAdded.hpp>
#include <tgbotxx/objects/ChatBoost.hpp>
#include <tgbotxx/objects/ChatBoostRemoved.hpp>
#include <tgbotxx/objects/ChatBoostSource.hpp>
#include <tgbotxx/objects/ChatBoostUpdated.hpp>
#include <tgbotxx/objects/ChatFullInfo.hpp>
#include <tgbotxx/objects/Chat.hpp>
#include <tgbotxx/objects/ChatInviteLink.hpp>
#include <tgbotxx/objects/ChatJoinRequest.hpp>
#include <tgbotxx/objects/ChatLocation.hpp>
#include <tgbotxx/objects/ChatMember.hpp>
#include <tgbotxx/objects/ChatMemberUpdated.hpp>
#include <tgbotxx/objects/ChatPermissions.hpp>
#include <tgbotxx/objects/ChatPhoto.hpp>
#include <tgbotxx/objects/ChatShared.hpp>
#include <tgbotxx/objects/Checklist.hpp>
#include <tgbotxx/objects/ChecklistTask.hpp>
#include <tgbotxx/objects/ChecklistTasksAdded.hpp>
#include <tgbotxx/objects/ChecklistTasksDone.hpp>
#include <tgbotxx/objects/ChosenInlineResult.hpp>
#include <tgbotxx/objects/Contact.hpp>
#include <tgbotxx/objects/CopyTextButton.hpp>
#include <tgbotxx/objects/Dice.hpp>
#include <tgbotxx/objects/DirectMessagePriceChanged.hpp>
#include <tgbotxx/objects/DirectMessagesTopic.hpp>
#include <tgbotxx/objects/Document.hpp>
#include <tgbotxx/objects/EncryptedCredentials.hpp>
#include <tgbotxx/objects/EncryptedPassportElement.hpp>
#include <tgbotxx/objects/ExternalReplyInfo.hpp>
#include <tgbotxx/objects/File.hpp>
#include <tgbotxx/objects/ForceReply.hpp>
#include <tgbotxx/objects/ForumTopicClosed.hpp>
#include <tgbotxx/objects/ForumTopicCreated.hpp>
#include <tgbotxx/objects/ForumTopicEdited.hpp>
#include <tgbotxx/objects/ForumTopic.hpp>
#include <tgbotxx/objects/ForumTopicReopened.hpp>
#include <tgbotxx/objects/GameHighScore.hpp>
#include <tgbotxx/objects/Game.hpp>
#include <tgbotxx/objects/GeneralForumTopicHidden.hpp>
#include <tgbotxx/objects/GeneralForumTopicUnhidden.hpp>
#include <tgbotxx/objects/Gift.hpp>
#include <tgbotxx/objects/GiftInfo.hpp>
#include <tgbotxx/objects/Gifts.hpp>
#include <tgbotxx/objects/GiveawayCompleted.hpp>
#include <tgbotxx/objects/GiveawayCreated.hpp>
#include <tgbotxx/objects/Giveaway.hpp>
#include <tgbotxx/objects/GiveawayWinners.hpp>
#include <tgbotxx/objects/InaccessibleMessage.hpp>
#include <tgbotxx/objects/InlineKeyboardButton.hpp>
#include <tgbotxx/objects/InlineKeyboardMarkup.hpp>
#include <tgbotxx/objects/InlineQuery.hpp>
#include <tgbotxx/objects/InlineQueryResult.hpp>
#include <tgbotxx/objects/InlineQueryResultsButton.hpp>
#include <tgbotxx/objects/InputChecklist.hpp>
#include <tgbotxx/objects/InputChecklistTask.hpp>
#include <tgbotxx/objects/InputMedia.hpp>
#include <tgbotxx/objects/InputMessageContent.hpp>
#include <tgbotxx/objects/InputPaidMedia.hpp>
#include <tgbotxx/objects/InputPollOption.hpp>
#include <tgbotxx/objects/InputProfilePhoto.hpp>
#include <tgbotxx/objects/InputSticker.hpp>
#include <tgbotxx/objects/InputStoryContent.hpp>
#include <tgbotxx/objects/Invoice.hpp>
#include <tgbotxx/objects/IReplyMarkup.hpp>
#include <tgbotxx/objects/KeyboardButton.hpp>
#include <tgbotxx/objects/KeyboardButtonPollType.hpp>
#include <tgbotxx/objects/KeyboardButtonRequestChat.hpp>
#include <tgbotxx/objects/KeyboardButtonRequestUsers.hpp>
#include <tgbotxx/objects/LabeledPrice.hpp>
#include <tgbotxx/objects/LinkPreviewOptions.hpp>
#include <tgbotxx/objects/LocationAddress.hpp>
#include <tgbotxx/objects/Location.hpp>
#include <tgbotxx/objects/LoginUrl.hpp>
#include <tgbotxx/objects/MaskPosition.hpp>
#include <tgbotxx/objects/MaybeInaccessibleMessage.hpp>
#include <tgbotxx/objects/MenuButton.hpp>
#include <tgbotxx/objects/MessageAutoDeleteTimerChanged.hpp>
#include <tgbotxx/objects/MessageEntity.hpp>
#include <tgbotxx/objects/Message.hpp>
#include <tgbotxx/objects/MessageId.hpp>
#include <tgbotxx/objects/MessageOrigin.hpp>
#include <tgbotxx/objects/MessageReactionCountUpdated.hpp>
#include <tgbotxx/objects/MessageReactionUpdated.hpp>
#include <tgbotxx/objects/Object.hpp>
#include <tgbotxx/objects/OrderInfo.hpp>
#include <tgbotxx/objects/OwnedGift.hpp>
#include <tgbotxx/objects/OwnedGifts.hpp>
#include <tgbotxx/objects/PaidMedia.hpp>
#include <tgbotxx/objects/PaidMediaInfo.hpp>
#include <tgbotxx/objects/PaidMediaPurchased.hpp>
#include <tgbotxx/objects/PaidMessagePriceChanged.hpp>
#include <tgbotxx/objects/PassportData.hpp>
#include <tgbotxx/objects/PassportElementError.hpp>
#include <tgbotxx/objects/PassportFile.hpp>
#include <tgbotxx/objects/PhotoSize.hpp>
#include <tgbotxx/objects/PollAnswer.hpp>
#include <tgbotxx/objects/Poll.hpp>
#include <tgbotxx/objects/PollOption.hpp>
#include <tgbotxx/objects/PreCheckoutQuery.hpp>
#include <tgbotxx/objects/ProximityAlertTriggered.hpp>
#include <tgbotxx/objects/ReactionCount.hpp>
#include <tgbotxx/objects/ReactionType.hpp>
#include <tgbotxx/objects/RefundedPayment.hpp>
#include <tgbotxx/objects/ReplyKeyboardMarkup.hpp>
#include <tgbotxx/objects/ReplyKeyboardRemove.hpp>
#include <tgbotxx/objects/ReplyParameters.hpp>
#include <tgbotxx/objects/RevenueWithdrawalState.hpp>
#include <tgbotxx/objects/SentWebAppMessage.hpp>
#include <tgbotxx/objects/SharedUser.hpp>
#include <tgbotxx/objects/ShippingAddress.hpp>
#include <tgbotxx/objects/ShippingOption.hpp>
#include <tgbotxx/objects/ShippingQuery.hpp>
#include <tgbotxx/objects/StarAmount.hpp>
#include <tgbotxx/objects/StarTransaction.hpp>
#include <tgbotxx/objects/StarTransactions.hpp>
#include <tgbotxx/objects/Sticker.hpp>
#include <tgbotxx/objects/StickerSet.hpp>
#include <tgbotxx/objects/StoryArea.hpp>
#include <tgbotxx/objects/StoryAreaPosition.hpp>
#include <tgbotxx/objects/StoryAreaType.hpp>
#include <tgbotxx/objects/Story.hpp>
#include <tgbotxx/objects/SuccessfulPayment.hpp>
#include <tgbotxx/objects/SuggestedPostApprovalFailed.hpp>
#include <tgbotxx/objects/SuggestedPostApproved.hpp>
#include <tgbotxx/objects/SuggestedPostDeclined.hpp>
#include <tgbotxx/objects/SuggestedPostInfo.hpp>
#include <tgbotxx/objects/SuggestedPostPaid.hpp>
#include <tgbotxx/objects/SuggestedPostParameters.hpp>
#include <tgbotxx/objects/SuggestedPostPrice.hpp>
#include <tgbotxx/objects/SuggestedPostRefunded.hpp>
#include <tgbotxx/objects/SwitchInlineQueryChosenChat.hpp>
#include <tgbotxx/objects/TextQuote.hpp>
#include <tgbotxx/objects/TransactionPartner.hpp>
#include <tgbotxx/objects/UniqueGiftBackdropColors.hpp>
#include <tgbotxx/objects/UniqueGiftBackdrop.hpp>
#include <tgbotxx/objects/UniqueGift.hpp>
#include <tgbotxx/objects/UniqueGiftInfo.hpp>
#include <tgbotxx/objects/UniqueGiftModel.hpp>
#include <tgbotxx/objects/UniqueGiftSymbol.hpp>
#include <tgbotxx/objects/Update.hpp>
#include <tgbotxx/objects/UserChatBoosts.hpp>
#include <tgbotxx/objects/User.hpp>
#include <tgbotxx/objects/UserProfilePhotos.hpp>
#include <tgbotxx/objects/UsersShared.hpp>
#include <tgbotxx/objects/Venue.hpp>
#include <tgbotxx/objects/VideoChatEnded.hpp>
#include <tgbotxx/objects/VideoChatParticipantsInvited.hpp>
#include <tgbotxx/objects/VideoChatScheduled.hpp>
#include <tgbotxx/objects/VideoChatStarted.hpp>
#include <tgbotxx/objects/Video.hpp>
#include <tgbotxx/objects/VideoNote.hpp>
#include <tgbotxx/objects/Voice.hpp>
#include <tgbotxx/objects/WebAppData.hpp>
#include <tgbotxx/objects/WebAppInfo.hpp>
#include <tgbotxx/objects/WebhookInfo.hpp>
#include <tgbotxx/objects/WriteAccessAllowed.hpp>

/// Utils
#include <tgbotxx/utils/DateTimeUtils.hpp>
#include <tgbotxx/utils/FileUtils.hpp>
#include <tgbotxx/utils/Ptr.hpp>
#include <tgbotxx/utils/StringUtils.hpp>
