var hierarchy =
[
    [ "tgbotxx::Animation", "structtgbotxx_1_1_animation.html", null ],
    [ "tgbotxx::Api", "classtgbotxx_1_1_api.html", null ],
    [ "tgbotxx::Audio", "structtgbotxx_1_1_audio.html", null ],
    [ "tgbotxx::Bot", "classtgbotxx_1_1_bot.html", null ],
    [ "tgbotxx::BotCommand", "structtgbotxx_1_1_bot_command.html", null ],
    [ "tgbotxx::BotCommandScope", "structtgbotxx_1_1_bot_command_scope.html", [
      [ "tgbotxx::BotCommandScopeAllChatAdministrators", "structtgbotxx_1_1_bot_command_scope_all_chat_administrators.html", null ],
      [ "tgbotxx::BotCommandScopeAllGroupChats", "structtgbotxx_1_1_bot_command_scope_all_group_chats.html", null ],
      [ "tgbotxx::BotCommandScopeAllPrivateChats", "structtgbotxx_1_1_bot_command_scope_all_private_chats.html", null ],
      [ "tgbotxx::BotCommandScopeChat", "structtgbotxx_1_1_bot_command_scope_chat.html", null ],
      [ "tgbotxx::BotCommandScopeChatAdministrators", "structtgbotxx_1_1_bot_command_scope_chat_administrators.html", null ],
      [ "tgbotxx::BotCommandScopeChatMember", "structtgbotxx_1_1_bot_command_scope_chat_member.html", null ],
      [ "tgbotxx::BotCommandScopeDefault", "structtgbotxx_1_1_bot_command_scope_default.html", null ]
    ] ],
    [ "tgbotxx::BotDescription", "structtgbotxx_1_1_bot_description.html", null ],
    [ "tgbotxx::BotName", "structtgbotxx_1_1_bot_name.html", null ],
    [ "tgbotxx::BotShortDescription", "structtgbotxx_1_1_bot_short_description.html", null ],
    [ "tgbotxx::CallbackGame", "structtgbotxx_1_1_callback_game.html", null ],
    [ "tgbotxx::CallbackQuery", "structtgbotxx_1_1_callback_query.html", null ],
    [ "tgbotxx::Chat", "structtgbotxx_1_1_chat.html", null ],
    [ "tgbotxx::ChatAdministratorRights", "structtgbotxx_1_1_chat_administrator_rights.html", null ],
    [ "tgbotxx::ChatInviteLink", "structtgbotxx_1_1_chat_invite_link.html", null ],
    [ "tgbotxx::ChatJoinRequest", "structtgbotxx_1_1_chat_join_request.html", null ],
    [ "tgbotxx::ChatLocation", "structtgbotxx_1_1_chat_location.html", null ],
    [ "tgbotxx::ChatMember", "structtgbotxx_1_1_chat_member.html", [
      [ "tgbotxx::ChatMemberAdministrator", "structtgbotxx_1_1_chat_member_administrator.html", null ],
      [ "tgbotxx::ChatMemberBanned", "structtgbotxx_1_1_chat_member_banned.html", null ],
      [ "tgbotxx::ChatMemberLeft", "structtgbotxx_1_1_chat_member_left.html", null ],
      [ "tgbotxx::ChatMemberMember", "structtgbotxx_1_1_chat_member_member.html", null ],
      [ "tgbotxx::ChatMemberOwner", "structtgbotxx_1_1_chat_member_owner.html", null ],
      [ "tgbotxx::ChatMemberRestricted", "structtgbotxx_1_1_chat_member_restricted.html", null ]
    ] ],
    [ "tgbotxx::ChatMemberUpdated", "structtgbotxx_1_1_chat_member_updated.html", null ],
    [ "tgbotxx::ChatPermissions", "structtgbotxx_1_1_chat_permissions.html", null ],
    [ "tgbotxx::ChatPhoto", "structtgbotxx_1_1_chat_photo.html", null ],
    [ "tgbotxx::ChatShared", "structtgbotxx_1_1_chat_shared.html", null ],
    [ "tgbotxx::ChosenInlineResult", "structtgbotxx_1_1_chosen_inline_result.html", null ],
    [ "tgbotxx::Contact", "structtgbotxx_1_1_contact.html", null ],
    [ "tgbotxx::Dice", "structtgbotxx_1_1_dice.html", null ],
    [ "tgbotxx::Document", "structtgbotxx_1_1_document.html", null ],
    [ "tgbotxx::EncryptedCredentials", "structtgbotxx_1_1_encrypted_credentials.html", null ],
    [ "tgbotxx::EncryptedPassportElement", "structtgbotxx_1_1_encrypted_passport_element.html", null ],
    [ "std::false_type", null, [
      [ "tgbotxx::isPtr< T >", "structtgbotxx_1_1is_ptr.html", null ]
    ] ],
    [ "tgbotxx::File", "structtgbotxx_1_1_file.html", null ],
    [ "tgbotxx::ForumTopic", "structtgbotxx_1_1_forum_topic.html", null ],
    [ "tgbotxx::ForumTopicClosed", "structtgbotxx_1_1_forum_topic_closed.html", null ],
    [ "tgbotxx::ForumTopicCreated", "structtgbotxx_1_1_forum_topic_created.html", null ],
    [ "tgbotxx::ForumTopicEdited", "structtgbotxx_1_1_forum_topic_edited.html", null ],
    [ "tgbotxx::ForumTopicReopened", "structtgbotxx_1_1_forum_topic_reopened.html", null ],
    [ "tgbotxx::Game", "structtgbotxx_1_1_game.html", null ],
    [ "tgbotxx::GeneralForumTopicHidden", "structtgbotxx_1_1_general_forum_topic_hidden.html", null ],
    [ "tgbotxx::GeneralForumTopicUnhidden", "structtgbotxx_1_1_general_forum_topic_unhidden.html", null ],
    [ "tgbotxx::InlineKeyboardButton", "structtgbotxx_1_1_inline_keyboard_button.html", null ],
    [ "tgbotxx::InlineQuery", "structtgbotxx_1_1_inline_query.html", null ],
    [ "tgbotxx::InlineQueryResult", "structtgbotxx_1_1_inline_query_result.html", [
      [ "tgbotxx::InlineQueryResultArticle", "structtgbotxx_1_1_inline_query_result_article.html", null ],
      [ "tgbotxx::InlineQueryResultGif", "structtgbotxx_1_1_inline_query_result_gif.html", null ],
      [ "tgbotxx::InlineQueryResultMpeg4Gif", "structtgbotxx_1_1_inline_query_result_mpeg4_gif.html", null ],
      [ "tgbotxx::InlineQueryResultPhoto", "structtgbotxx_1_1_inline_query_result_photo.html", null ],
      [ "tgbotxx::InlineQueryResultVideo", "structtgbotxx_1_1_inline_query_result_video.html", null ]
    ] ],
    [ "tgbotxx::InlineQueryResultsButton", "structtgbotxx_1_1_inline_query_results_button.html", null ],
    [ "tgbotxx::InputMedia", "structtgbotxx_1_1_input_media.html", [
      [ "tgbotxx::InputMediaAnimation", "structtgbotxx_1_1_input_media_animation.html", null ],
      [ "tgbotxx::InputMediaAudio", "structtgbotxx_1_1_input_media_audio.html", null ],
      [ "tgbotxx::InputMediaDocument", "structtgbotxx_1_1_input_media_document.html", null ],
      [ "tgbotxx::InputMediaPhoto", "structtgbotxx_1_1_input_media_photo.html", null ],
      [ "tgbotxx::InputMediaVideo", "structtgbotxx_1_1_input_media_video.html", null ]
    ] ],
    [ "tgbotxx::InputMessageContent", "structtgbotxx_1_1_input_message_content.html", [
      [ "tgbotxx::InputContactMessageContent", "structtgbotxx_1_1_input_contact_message_content.html", null ],
      [ "tgbotxx::InputInvoiceMessageContent", "structtgbotxx_1_1_input_invoice_message_content.html", null ],
      [ "tgbotxx::InputLocationMessageContent", "structtgbotxx_1_1_input_location_message_content.html", null ],
      [ "tgbotxx::InputTextMessageContent", "structtgbotxx_1_1_input_text_message_content.html", null ],
      [ "tgbotxx::InputVenueMessageContent", "structtgbotxx_1_1_input_venue_message_content.html", null ]
    ] ],
    [ "tgbotxx::Invoice", "structtgbotxx_1_1_invoice.html", null ],
    [ "tgbotxx::IReplyMarkup", "structtgbotxx_1_1_i_reply_markup.html", [
      [ "tgbotxx::ForceReply", "structtgbotxx_1_1_force_reply.html", null ],
      [ "tgbotxx::InlineKeyboardMarkup", "structtgbotxx_1_1_inline_keyboard_markup.html", null ],
      [ "tgbotxx::ReplyKeyboardMarkup", "structtgbotxx_1_1_reply_keyboard_markup.html", null ],
      [ "tgbotxx::ReplyKeyboardRemove", "structtgbotxx_1_1_reply_keyboard_remove.html", null ]
    ] ],
    [ "tgbotxx::KeyboardButton", "structtgbotxx_1_1_keyboard_button.html", null ],
    [ "tgbotxx::KeyboardButtonPollType", "structtgbotxx_1_1_keyboard_button_poll_type.html", null ],
    [ "tgbotxx::KeyboardButtonRequestChat", "structtgbotxx_1_1_keyboard_button_request_chat.html", null ],
    [ "tgbotxx::KeyboardButtonRequestUser", "structtgbotxx_1_1_keyboard_button_request_user.html", null ],
    [ "tgbotxx::LabeledPrice", "structtgbotxx_1_1_labeled_price.html", null ],
    [ "tgbotxx::Location", "structtgbotxx_1_1_location.html", null ],
    [ "tgbotxx::LoginUrl", "structtgbotxx_1_1_login_url.html", null ],
    [ "tgbotxx::MaskPosition", "structtgbotxx_1_1_mask_position.html", null ],
    [ "tgbotxx::MenuButton", "structtgbotxx_1_1_menu_button.html", [
      [ "tgbotxx::MenuButtonCommands", "structtgbotxx_1_1_menu_button_commands.html", null ],
      [ "tgbotxx::MenuButtonDefault", "structtgbotxx_1_1_menu_button_default.html", null ],
      [ "tgbotxx::MenuButtonWebApp", "structtgbotxx_1_1_menu_button_web_app.html", null ]
    ] ],
    [ "tgbotxx::Message", "structtgbotxx_1_1_message.html", null ],
    [ "tgbotxx::MessageAutoDeleteTimerChanged", "structtgbotxx_1_1_message_auto_delete_timer_changed.html", null ],
    [ "tgbotxx::MessageEntity", "structtgbotxx_1_1_message_entity.html", null ],
    [ "tgbotxx::MessageId", "structtgbotxx_1_1_message_id.html", null ],
    [ "tgbotxx::OrderInfo", "structtgbotxx_1_1_order_info.html", null ],
    [ "tgbotxx::PassportData", "structtgbotxx_1_1_passport_data.html", null ],
    [ "tgbotxx::PassportFile", "structtgbotxx_1_1_passport_file.html", null ],
    [ "tgbotxx::PhotoSize", "structtgbotxx_1_1_photo_size.html", null ],
    [ "tgbotxx::Poll", "structtgbotxx_1_1_poll.html", null ],
    [ "tgbotxx::PollAnswer", "structtgbotxx_1_1_poll_answer.html", null ],
    [ "tgbotxx::PollOption", "structtgbotxx_1_1_poll_option.html", null ],
    [ "tgbotxx::PreCheckoutQuery", "structtgbotxx_1_1_pre_checkout_query.html", null ],
    [ "tgbotxx::ProximityAlertTriggered", "structtgbotxx_1_1_proximity_alert_triggered.html", null ],
    [ "std::runtime_error", null, [
      [ "tgbotxx::Exception", "classtgbotxx_1_1_exception.html", null ]
    ] ],
    [ "tgbotxx::ShippingAddress", "structtgbotxx_1_1_shipping_address.html", null ],
    [ "tgbotxx::ShippingQuery", "structtgbotxx_1_1_shipping_query.html", null ],
    [ "tgbotxx::Sticker", "structtgbotxx_1_1_sticker.html", null ],
    [ "tgbotxx::Story", "structtgbotxx_1_1_story.html", null ],
    [ "tgbotxx::SuccessfulPayment", "structtgbotxx_1_1_successful_payment.html", null ],
    [ "tgbotxx::SwitchInlineQueryChosenChat", "structtgbotxx_1_1_switch_inline_query_chosen_chat.html", null ],
    [ "std::true_type", null, [
      [ "tgbotxx::isPtr< CPtr< T > >", "structtgbotxx_1_1is_ptr_3_01_c_ptr_3_01_t_01_4_01_4.html", null ],
      [ "tgbotxx::isPtr< CPtrC< T > >", "structtgbotxx_1_1is_ptr_3_01_c_ptr_c_3_01_t_01_4_01_4.html", null ],
      [ "tgbotxx::isPtr< Ptr< T > >", "structtgbotxx_1_1is_ptr_3_01_ptr_3_01_t_01_4_01_4.html", null ],
      [ "tgbotxx::isPtr< PtrC< T > >", "structtgbotxx_1_1is_ptr_3_01_ptr_c_3_01_t_01_4_01_4.html", null ]
    ] ],
    [ "tgbotxx::Update", "structtgbotxx_1_1_update.html", null ],
    [ "tgbotxx::User", "structtgbotxx_1_1_user.html", null ],
    [ "tgbotxx::UserProfilePhotos", "structtgbotxx_1_1_user_profile_photos.html", null ],
    [ "tgbotxx::UserShared", "structtgbotxx_1_1_user_shared.html", null ],
    [ "tgbotxx::Venue", "structtgbotxx_1_1_venue.html", null ],
    [ "tgbotxx::Video", "structtgbotxx_1_1_video.html", null ],
    [ "tgbotxx::VideoChatEnded", "structtgbotxx_1_1_video_chat_ended.html", null ],
    [ "tgbotxx::VideoChatParticipantsInvited", "structtgbotxx_1_1_video_chat_participants_invited.html", null ],
    [ "tgbotxx::VideoChatScheduled", "structtgbotxx_1_1_video_chat_scheduled.html", null ],
    [ "tgbotxx::VideoChatStarted", "structtgbotxx_1_1_video_chat_started.html", null ],
    [ "tgbotxx::VideoNote", "structtgbotxx_1_1_video_note.html", null ],
    [ "tgbotxx::Voice", "structtgbotxx_1_1_voice.html", null ],
    [ "tgbotxx::WebAppData", "structtgbotxx_1_1_web_app_data.html", null ],
    [ "tgbotxx::WebAppInfo", "structtgbotxx_1_1_web_app_info.html", null ],
    [ "tgbotxx::WebhookInfo", "structtgbotxx_1_1_webhook_info.html", null ],
    [ "tgbotxx::WriteAccessAllowed", "structtgbotxx_1_1_write_access_allowed.html", null ]
];