var searchData=
[
  ['inlinekeyboardbutton_901',['InlineKeyboardButton',['../structtgbotxx_1_1_inline_keyboard_button.html',1,'tgbotxx']]],
  ['inlinekeyboardmarkup_902',['InlineKeyboardMarkup',['../structtgbotxx_1_1_inline_keyboard_markup.html',1,'tgbotxx']]],
  ['inlinequery_903',['InlineQuery',['../structtgbotxx_1_1_inline_query.html',1,'tgbotxx']]],
  ['inlinequeryresult_904',['InlineQueryResult',['../structtgbotxx_1_1_inline_query_result.html',1,'tgbotxx']]],
  ['inlinequeryresultarticle_905',['InlineQueryResultArticle',['../structtgbotxx_1_1_inline_query_result_article.html',1,'tgbotxx']]],
  ['inlinequeryresultaudio_906',['InlineQueryResultAudio',['../structtgbotxx_1_1_inline_query_result_audio.html',1,'tgbotxx']]],
  ['inlinequeryresultcachedaudio_907',['InlineQueryResultCachedAudio',['../structtgbotxx_1_1_inline_query_result_cached_audio.html',1,'tgbotxx']]],
  ['inlinequeryresultcacheddocument_908',['InlineQueryResultCachedDocument',['../structtgbotxx_1_1_inline_query_result_cached_document.html',1,'tgbotxx']]],
  ['inlinequeryresultcachedgif_909',['InlineQueryResultCachedGif',['../structtgbotxx_1_1_inline_query_result_cached_gif.html',1,'tgbotxx']]],
  ['inlinequeryresultcachedmpeg4gif_910',['InlineQueryResultCachedMpeg4Gif',['../structtgbotxx_1_1_inline_query_result_cached_mpeg4_gif.html',1,'tgbotxx']]],
  ['inlinequeryresultcachedphoto_911',['InlineQueryResultCachedPhoto',['../structtgbotxx_1_1_inline_query_result_cached_photo.html',1,'tgbotxx']]],
  ['inlinequeryresultcachedsticker_912',['InlineQueryResultCachedSticker',['../structtgbotxx_1_1_inline_query_result_cached_sticker.html',1,'tgbotxx']]],
  ['inlinequeryresultcachedvideo_913',['InlineQueryResultCachedVideo',['../structtgbotxx_1_1_inline_query_result_cached_video.html',1,'tgbotxx']]],
  ['inlinequeryresultcachedvoice_914',['InlineQueryResultCachedVoice',['../structtgbotxx_1_1_inline_query_result_cached_voice.html',1,'tgbotxx']]],
  ['inlinequeryresultcontact_915',['InlineQueryResultContact',['../structtgbotxx_1_1_inline_query_result_contact.html',1,'tgbotxx']]],
  ['inlinequeryresultdocument_916',['InlineQueryResultDocument',['../structtgbotxx_1_1_inline_query_result_document.html',1,'tgbotxx']]],
  ['inlinequeryresultgame_917',['InlineQueryResultGame',['../structtgbotxx_1_1_inline_query_result_game.html',1,'tgbotxx']]],
  ['inlinequeryresultgif_918',['InlineQueryResultGif',['../structtgbotxx_1_1_inline_query_result_gif.html',1,'tgbotxx']]],
  ['inlinequeryresultlocation_919',['InlineQueryResultLocation',['../structtgbotxx_1_1_inline_query_result_location.html',1,'tgbotxx']]],
  ['inlinequeryresultmpeg4gif_920',['InlineQueryResultMpeg4Gif',['../structtgbotxx_1_1_inline_query_result_mpeg4_gif.html',1,'tgbotxx']]],
  ['inlinequeryresultphoto_921',['InlineQueryResultPhoto',['../structtgbotxx_1_1_inline_query_result_photo.html',1,'tgbotxx']]],
  ['inlinequeryresultsbutton_922',['InlineQueryResultsButton',['../structtgbotxx_1_1_inline_query_results_button.html',1,'tgbotxx']]],
  ['inlinequeryresultvenue_923',['InlineQueryResultVenue',['../structtgbotxx_1_1_inline_query_result_venue.html',1,'tgbotxx']]],
  ['inlinequeryresultvideo_924',['InlineQueryResultVideo',['../structtgbotxx_1_1_inline_query_result_video.html',1,'tgbotxx']]],
  ['inlinequeryresultvoice_925',['InlineQueryResultVoice',['../structtgbotxx_1_1_inline_query_result_voice.html',1,'tgbotxx']]],
  ['inputcontactmessagecontent_926',['InputContactMessageContent',['../structtgbotxx_1_1_input_contact_message_content.html',1,'tgbotxx']]],
  ['inputinvoicemessagecontent_927',['InputInvoiceMessageContent',['../structtgbotxx_1_1_input_invoice_message_content.html',1,'tgbotxx']]],
  ['inputlocationmessagecontent_928',['InputLocationMessageContent',['../structtgbotxx_1_1_input_location_message_content.html',1,'tgbotxx']]],
  ['inputmedia_929',['InputMedia',['../structtgbotxx_1_1_input_media.html',1,'tgbotxx']]],
  ['inputmediaanimation_930',['InputMediaAnimation',['../structtgbotxx_1_1_input_media_animation.html',1,'tgbotxx']]],
  ['inputmediaaudio_931',['InputMediaAudio',['../structtgbotxx_1_1_input_media_audio.html',1,'tgbotxx']]],
  ['inputmediadocument_932',['InputMediaDocument',['../structtgbotxx_1_1_input_media_document.html',1,'tgbotxx']]],
  ['inputmediaphoto_933',['InputMediaPhoto',['../structtgbotxx_1_1_input_media_photo.html',1,'tgbotxx']]],
  ['inputmediavideo_934',['InputMediaVideo',['../structtgbotxx_1_1_input_media_video.html',1,'tgbotxx']]],
  ['inputmessagecontent_935',['InputMessageContent',['../structtgbotxx_1_1_input_message_content.html',1,'tgbotxx']]],
  ['inputtextmessagecontent_936',['InputTextMessageContent',['../structtgbotxx_1_1_input_text_message_content.html',1,'tgbotxx']]],
  ['inputvenuemessagecontent_937',['InputVenueMessageContent',['../structtgbotxx_1_1_input_venue_message_content.html',1,'tgbotxx']]],
  ['invoice_938',['Invoice',['../structtgbotxx_1_1_invoice.html',1,'tgbotxx']]],
  ['ireplymarkup_939',['IReplyMarkup',['../structtgbotxx_1_1_i_reply_markup.html',1,'tgbotxx']]],
  ['isptr_940',['isPtr',['../structtgbotxx_1_1is_ptr.html',1,'tgbotxx']]],
  ['isptr_3c_20cptr_3c_20t_20_3e_20_3e_941',['isPtr&lt; CPtr&lt; T &gt; &gt;',['../structtgbotxx_1_1is_ptr_3_01_c_ptr_3_01_t_01_4_01_4.html',1,'tgbotxx']]],
  ['isptr_3c_20cptrc_3c_20t_20_3e_20_3e_942',['isPtr&lt; CPtrC&lt; T &gt; &gt;',['../structtgbotxx_1_1is_ptr_3_01_c_ptr_c_3_01_t_01_4_01_4.html',1,'tgbotxx']]],
  ['isptr_3c_20ptr_3c_20t_20_3e_20_3e_943',['isPtr&lt; Ptr&lt; T &gt; &gt;',['../structtgbotxx_1_1is_ptr_3_01_ptr_3_01_t_01_4_01_4.html',1,'tgbotxx']]],
  ['isptr_3c_20ptrc_3c_20t_20_3e_20_3e_944',['isPtr&lt; PtrC&lt; T &gt; &gt;',['../structtgbotxx_1_1is_ptr_3_01_ptr_c_3_01_t_01_4_01_4.html',1,'tgbotxx']]]
];
