var searchData=
[
  ['callbackgame_663',['CallbackGame',['../structtgbotxx_1_1_callback_game.html',1,'tgbotxx']]],
  ['callbackquery_664',['CallbackQuery',['../structtgbotxx_1_1_callback_query.html',1,'tgbotxx']]],
  ['chat_665',['Chat',['../structtgbotxx_1_1_chat.html',1,'tgbotxx']]],
  ['chatadministratorrights_666',['ChatAdministratorRights',['../structtgbotxx_1_1_chat_administrator_rights.html',1,'tgbotxx']]],
  ['chatinvitelink_667',['ChatInviteLink',['../structtgbotxx_1_1_chat_invite_link.html',1,'tgbotxx']]],
  ['chatjoinrequest_668',['ChatJoinRequest',['../structtgbotxx_1_1_chat_join_request.html',1,'tgbotxx']]],
  ['chatlocation_669',['ChatLocation',['../structtgbotxx_1_1_chat_location.html',1,'tgbotxx']]],
  ['chatmember_670',['ChatMember',['../structtgbotxx_1_1_chat_member.html',1,'tgbotxx']]],
  ['chatmemberadministrator_671',['ChatMemberAdministrator',['../structtgbotxx_1_1_chat_member_administrator.html',1,'tgbotxx']]],
  ['chatmemberbanned_672',['ChatMemberBanned',['../structtgbotxx_1_1_chat_member_banned.html',1,'tgbotxx']]],
  ['chatmemberleft_673',['ChatMemberLeft',['../structtgbotxx_1_1_chat_member_left.html',1,'tgbotxx']]],
  ['chatmembermember_674',['ChatMemberMember',['../structtgbotxx_1_1_chat_member_member.html',1,'tgbotxx']]],
  ['chatmemberowner_675',['ChatMemberOwner',['../structtgbotxx_1_1_chat_member_owner.html',1,'tgbotxx']]],
  ['chatmemberrestricted_676',['ChatMemberRestricted',['../structtgbotxx_1_1_chat_member_restricted.html',1,'tgbotxx']]],
  ['chatmemberupdated_677',['ChatMemberUpdated',['../structtgbotxx_1_1_chat_member_updated.html',1,'tgbotxx']]],
  ['chatpermissions_678',['ChatPermissions',['../structtgbotxx_1_1_chat_permissions.html',1,'tgbotxx']]],
  ['chatphoto_679',['ChatPhoto',['../structtgbotxx_1_1_chat_photo.html',1,'tgbotxx']]],
  ['chatshared_680',['ChatShared',['../structtgbotxx_1_1_chat_shared.html',1,'tgbotxx']]],
  ['choseninlineresult_681',['ChosenInlineResult',['../structtgbotxx_1_1_chosen_inline_result.html',1,'tgbotxx']]],
  ['contact_682',['Contact',['../structtgbotxx_1_1_contact.html',1,'tgbotxx']]]
];
