var searchData=
[
  ['paidsubscriptionbot_1090',['PaidSubscriptionBot',['../class_paid_subscription_bot.html',1,'']]],
  ['passportdata_1091',['PassportData',['../structtgbotxx_1_1_passport_data.html',1,'tgbotxx']]],
  ['passportelementerror_1092',['PassportElementError',['../structtgbotxx_1_1_passport_element_error.html',1,'tgbotxx']]],
  ['passportelementerrordatafield_1093',['PassportElementErrorDataField',['../structtgbotxx_1_1_passport_element_error_data_field.html',1,'tgbotxx']]],
  ['passportelementerrorfile_1094',['PassportElementErrorFile',['../structtgbotxx_1_1_passport_element_error_file.html',1,'tgbotxx']]],
  ['passportelementerrorfiles_1095',['PassportElementErrorFiles',['../structtgbotxx_1_1_passport_element_error_files.html',1,'tgbotxx']]],
  ['passportelementerrorfrontside_1096',['PassportElementErrorFrontSide',['../structtgbotxx_1_1_passport_element_error_front_side.html',1,'tgbotxx']]],
  ['passportelementerrorreverseside_1097',['PassportElementErrorReverseSide',['../structtgbotxx_1_1_passport_element_error_reverse_side.html',1,'tgbotxx']]],
  ['passportelementerrorselfie_1098',['PassportElementErrorSelfie',['../structtgbotxx_1_1_passport_element_error_selfie.html',1,'tgbotxx']]],
  ['passportelementerrortranslationfile_1099',['PassportElementErrorTranslationFile',['../structtgbotxx_1_1_passport_element_error_translation_file.html',1,'tgbotxx']]],
  ['passportelementerrortranslationfiles_1100',['PassportElementErrorTranslationFiles',['../structtgbotxx_1_1_passport_element_error_translation_files.html',1,'tgbotxx']]],
  ['passportelementerrorunspecified_1101',['PassportElementErrorUnspecified',['../structtgbotxx_1_1_passport_element_error_unspecified.html',1,'tgbotxx']]],
  ['passportfile_1102',['PassportFile',['../structtgbotxx_1_1_passport_file.html',1,'tgbotxx']]],
  ['photosize_1103',['PhotoSize',['../structtgbotxx_1_1_photo_size.html',1,'tgbotxx']]],
  ['poll_1104',['Poll',['../structtgbotxx_1_1_poll.html',1,'tgbotxx']]],
  ['pollanswer_1105',['PollAnswer',['../structtgbotxx_1_1_poll_answer.html',1,'tgbotxx']]],
  ['polloption_1106',['PollOption',['../structtgbotxx_1_1_poll_option.html',1,'tgbotxx']]],
  ['precheckoutquery_1107',['PreCheckoutQuery',['../structtgbotxx_1_1_pre_checkout_query.html',1,'tgbotxx']]],
  ['proximityalerttriggered_1108',['ProximityAlertTriggered',['../structtgbotxx_1_1_proximity_alert_triggered.html',1,'tgbotxx']]]
];
