var searchData=
[
  ['paidsubscriptionbot_1034',['PaidSubscriptionBot',['../class_paid_subscription_bot.html',1,'']]],
  ['passportdata_1035',['PassportData',['../structtgbotxx_1_1_passport_data.html',1,'tgbotxx']]],
  ['passportelementerror_1036',['PassportElementError',['../structtgbotxx_1_1_passport_element_error.html',1,'tgbotxx']]],
  ['passportelementerrordatafield_1037',['PassportElementErrorDataField',['../structtgbotxx_1_1_passport_element_error_data_field.html',1,'tgbotxx']]],
  ['passportelementerrorfile_1038',['PassportElementErrorFile',['../structtgbotxx_1_1_passport_element_error_file.html',1,'tgbotxx']]],
  ['passportelementerrorfiles_1039',['PassportElementErrorFiles',['../structtgbotxx_1_1_passport_element_error_files.html',1,'tgbotxx']]],
  ['passportelementerrorfrontside_1040',['PassportElementErrorFrontSide',['../structtgbotxx_1_1_passport_element_error_front_side.html',1,'tgbotxx']]],
  ['passportelementerrorreverseside_1041',['PassportElementErrorReverseSide',['../structtgbotxx_1_1_passport_element_error_reverse_side.html',1,'tgbotxx']]],
  ['passportelementerrorselfie_1042',['PassportElementErrorSelfie',['../structtgbotxx_1_1_passport_element_error_selfie.html',1,'tgbotxx']]],
  ['passportelementerrortranslationfile_1043',['PassportElementErrorTranslationFile',['../structtgbotxx_1_1_passport_element_error_translation_file.html',1,'tgbotxx']]],
  ['passportelementerrortranslationfiles_1044',['PassportElementErrorTranslationFiles',['../structtgbotxx_1_1_passport_element_error_translation_files.html',1,'tgbotxx']]],
  ['passportelementerrorunspecified_1045',['PassportElementErrorUnspecified',['../structtgbotxx_1_1_passport_element_error_unspecified.html',1,'tgbotxx']]],
  ['passportfile_1046',['PassportFile',['../structtgbotxx_1_1_passport_file.html',1,'tgbotxx']]],
  ['photosize_1047',['PhotoSize',['../structtgbotxx_1_1_photo_size.html',1,'tgbotxx']]],
  ['poll_1048',['Poll',['../structtgbotxx_1_1_poll.html',1,'tgbotxx']]],
  ['pollanswer_1049',['PollAnswer',['../structtgbotxx_1_1_poll_answer.html',1,'tgbotxx']]],
  ['polloption_1050',['PollOption',['../structtgbotxx_1_1_poll_option.html',1,'tgbotxx']]],
  ['precheckoutquery_1051',['PreCheckoutQuery',['../structtgbotxx_1_1_pre_checkout_query.html',1,'tgbotxx']]],
  ['proximityalerttriggered_1052',['ProximityAlertTriggered',['../structtgbotxx_1_1_proximity_alert_triggered.html',1,'tgbotxx']]]
];
