var searchData=
[
  ['inlinekeyboardbutton_890',['InlineKeyboardButton',['../structtgbotxx_1_1_inline_keyboard_button.html',1,'tgbotxx']]],
  ['inlinekeyboardmarkup_891',['InlineKeyboardMarkup',['../structtgbotxx_1_1_inline_keyboard_markup.html',1,'tgbotxx']]],
  ['inlinequery_892',['InlineQuery',['../structtgbotxx_1_1_inline_query.html',1,'tgbotxx']]],
  ['inlinequeryresult_893',['InlineQueryResult',['../structtgbotxx_1_1_inline_query_result.html',1,'tgbotxx']]],
  ['inlinequeryresultarticle_894',['InlineQueryResultArticle',['../structtgbotxx_1_1_inline_query_result_article.html',1,'tgbotxx']]],
  ['inlinequeryresultaudio_895',['InlineQueryResultAudio',['../structtgbotxx_1_1_inline_query_result_audio.html',1,'tgbotxx']]],
  ['inlinequeryresultcachedphoto_896',['InlineQueryResultCachedPhoto',['../structtgbotxx_1_1_inline_query_result_cached_photo.html',1,'tgbotxx']]],
  ['inlinequeryresultcontact_897',['InlineQueryResultContact',['../structtgbotxx_1_1_inline_query_result_contact.html',1,'tgbotxx']]],
  ['inlinequeryresultdocument_898',['InlineQueryResultDocument',['../structtgbotxx_1_1_inline_query_result_document.html',1,'tgbotxx']]],
  ['inlinequeryresultgame_899',['InlineQueryResultGame',['../structtgbotxx_1_1_inline_query_result_game.html',1,'tgbotxx']]],
  ['inlinequeryresultgif_900',['InlineQueryResultGif',['../structtgbotxx_1_1_inline_query_result_gif.html',1,'tgbotxx']]],
  ['inlinequeryresultlocation_901',['InlineQueryResultLocation',['../structtgbotxx_1_1_inline_query_result_location.html',1,'tgbotxx']]],
  ['inlinequeryresultmpeg4gif_902',['InlineQueryResultMpeg4Gif',['../structtgbotxx_1_1_inline_query_result_mpeg4_gif.html',1,'tgbotxx']]],
  ['inlinequeryresultphoto_903',['InlineQueryResultPhoto',['../structtgbotxx_1_1_inline_query_result_photo.html',1,'tgbotxx']]],
  ['inlinequeryresultsbutton_904',['InlineQueryResultsButton',['../structtgbotxx_1_1_inline_query_results_button.html',1,'tgbotxx']]],
  ['inlinequeryresultvenue_905',['InlineQueryResultVenue',['../structtgbotxx_1_1_inline_query_result_venue.html',1,'tgbotxx']]],
  ['inlinequeryresultvideo_906',['InlineQueryResultVideo',['../structtgbotxx_1_1_inline_query_result_video.html',1,'tgbotxx']]],
  ['inlinequeryresultvoice_907',['InlineQueryResultVoice',['../structtgbotxx_1_1_inline_query_result_voice.html',1,'tgbotxx']]],
  ['inputcontactmessagecontent_908',['InputContactMessageContent',['../structtgbotxx_1_1_input_contact_message_content.html',1,'tgbotxx']]],
  ['inputinvoicemessagecontent_909',['InputInvoiceMessageContent',['../structtgbotxx_1_1_input_invoice_message_content.html',1,'tgbotxx']]],
  ['inputlocationmessagecontent_910',['InputLocationMessageContent',['../structtgbotxx_1_1_input_location_message_content.html',1,'tgbotxx']]],
  ['inputmedia_911',['InputMedia',['../structtgbotxx_1_1_input_media.html',1,'tgbotxx']]],
  ['inputmediaanimation_912',['InputMediaAnimation',['../structtgbotxx_1_1_input_media_animation.html',1,'tgbotxx']]],
  ['inputmediaaudio_913',['InputMediaAudio',['../structtgbotxx_1_1_input_media_audio.html',1,'tgbotxx']]],
  ['inputmediadocument_914',['InputMediaDocument',['../structtgbotxx_1_1_input_media_document.html',1,'tgbotxx']]],
  ['inputmediaphoto_915',['InputMediaPhoto',['../structtgbotxx_1_1_input_media_photo.html',1,'tgbotxx']]],
  ['inputmediavideo_916',['InputMediaVideo',['../structtgbotxx_1_1_input_media_video.html',1,'tgbotxx']]],
  ['inputmessagecontent_917',['InputMessageContent',['../structtgbotxx_1_1_input_message_content.html',1,'tgbotxx']]],
  ['inputtextmessagecontent_918',['InputTextMessageContent',['../structtgbotxx_1_1_input_text_message_content.html',1,'tgbotxx']]],
  ['inputvenuemessagecontent_919',['InputVenueMessageContent',['../structtgbotxx_1_1_input_venue_message_content.html',1,'tgbotxx']]],
  ['invoice_920',['Invoice',['../structtgbotxx_1_1_invoice.html',1,'tgbotxx']]],
  ['ireplymarkup_921',['IReplyMarkup',['../structtgbotxx_1_1_i_reply_markup.html',1,'tgbotxx']]],
  ['isptr_922',['isPtr',['../structtgbotxx_1_1is_ptr.html',1,'tgbotxx']]],
  ['isptr_3c_20cptr_3c_20t_20_3e_20_3e_923',['isPtr&lt; CPtr&lt; T &gt; &gt;',['../structtgbotxx_1_1is_ptr_3_01_c_ptr_3_01_t_01_4_01_4.html',1,'tgbotxx']]],
  ['isptr_3c_20cptrc_3c_20t_20_3e_20_3e_924',['isPtr&lt; CPtrC&lt; T &gt; &gt;',['../structtgbotxx_1_1is_ptr_3_01_c_ptr_c_3_01_t_01_4_01_4.html',1,'tgbotxx']]],
  ['isptr_3c_20ptr_3c_20t_20_3e_20_3e_925',['isPtr&lt; Ptr&lt; T &gt; &gt;',['../structtgbotxx_1_1is_ptr_3_01_ptr_3_01_t_01_4_01_4.html',1,'tgbotxx']]],
  ['isptr_3c_20ptrc_3c_20t_20_3e_20_3e_926',['isPtr&lt; PtrC&lt; T &gt; &gt;',['../structtgbotxx_1_1is_ptr_3_01_ptr_c_3_01_t_01_4_01_4.html',1,'tgbotxx']]]
];
