var searchData=
[
  ['inlinekeyboardbutton_878',['InlineKeyboardButton',['../structtgbotxx_1_1_inline_keyboard_button.html',1,'tgbotxx']]],
  ['inlinekeyboardmarkup_879',['InlineKeyboardMarkup',['../structtgbotxx_1_1_inline_keyboard_markup.html',1,'tgbotxx']]],
  ['inlinequery_880',['InlineQuery',['../structtgbotxx_1_1_inline_query.html',1,'tgbotxx']]],
  ['inlinequeryresult_881',['InlineQueryResult',['../structtgbotxx_1_1_inline_query_result.html',1,'tgbotxx']]],
  ['inlinequeryresultarticle_882',['InlineQueryResultArticle',['../structtgbotxx_1_1_inline_query_result_article.html',1,'tgbotxx']]],
  ['inlinequeryresultgif_883',['InlineQueryResultGif',['../structtgbotxx_1_1_inline_query_result_gif.html',1,'tgbotxx']]],
  ['inlinequeryresultmpeg4gif_884',['InlineQueryResultMpeg4Gif',['../structtgbotxx_1_1_inline_query_result_mpeg4_gif.html',1,'tgbotxx']]],
  ['inlinequeryresultphoto_885',['InlineQueryResultPhoto',['../structtgbotxx_1_1_inline_query_result_photo.html',1,'tgbotxx']]],
  ['inlinequeryresultsbutton_886',['InlineQueryResultsButton',['../structtgbotxx_1_1_inline_query_results_button.html',1,'tgbotxx']]],
  ['inlinequeryresultvideo_887',['InlineQueryResultVideo',['../structtgbotxx_1_1_inline_query_result_video.html',1,'tgbotxx']]],
  ['inputcontactmessagecontent_888',['InputContactMessageContent',['../structtgbotxx_1_1_input_contact_message_content.html',1,'tgbotxx']]],
  ['inputinvoicemessagecontent_889',['InputInvoiceMessageContent',['../structtgbotxx_1_1_input_invoice_message_content.html',1,'tgbotxx']]],
  ['inputlocationmessagecontent_890',['InputLocationMessageContent',['../structtgbotxx_1_1_input_location_message_content.html',1,'tgbotxx']]],
  ['inputmedia_891',['InputMedia',['../structtgbotxx_1_1_input_media.html',1,'tgbotxx']]],
  ['inputmediaanimation_892',['InputMediaAnimation',['../structtgbotxx_1_1_input_media_animation.html',1,'tgbotxx']]],
  ['inputmediaaudio_893',['InputMediaAudio',['../structtgbotxx_1_1_input_media_audio.html',1,'tgbotxx']]],
  ['inputmediadocument_894',['InputMediaDocument',['../structtgbotxx_1_1_input_media_document.html',1,'tgbotxx']]],
  ['inputmediaphoto_895',['InputMediaPhoto',['../structtgbotxx_1_1_input_media_photo.html',1,'tgbotxx']]],
  ['inputmediavideo_896',['InputMediaVideo',['../structtgbotxx_1_1_input_media_video.html',1,'tgbotxx']]],
  ['inputmessagecontent_897',['InputMessageContent',['../structtgbotxx_1_1_input_message_content.html',1,'tgbotxx']]],
  ['inputtextmessagecontent_898',['InputTextMessageContent',['../structtgbotxx_1_1_input_text_message_content.html',1,'tgbotxx']]],
  ['inputvenuemessagecontent_899',['InputVenueMessageContent',['../structtgbotxx_1_1_input_venue_message_content.html',1,'tgbotxx']]],
  ['invoice_900',['Invoice',['../structtgbotxx_1_1_invoice.html',1,'tgbotxx']]],
  ['ireplymarkup_901',['IReplyMarkup',['../structtgbotxx_1_1_i_reply_markup.html',1,'tgbotxx']]],
  ['isptr_902',['isPtr',['../structtgbotxx_1_1is_ptr.html',1,'tgbotxx']]],
  ['isptr_3c_20cptr_3c_20t_20_3e_20_3e_903',['isPtr&lt; CPtr&lt; T &gt; &gt;',['../structtgbotxx_1_1is_ptr_3_01_c_ptr_3_01_t_01_4_01_4.html',1,'tgbotxx']]],
  ['isptr_3c_20cptrc_3c_20t_20_3e_20_3e_904',['isPtr&lt; CPtrC&lt; T &gt; &gt;',['../structtgbotxx_1_1is_ptr_3_01_c_ptr_c_3_01_t_01_4_01_4.html',1,'tgbotxx']]],
  ['isptr_3c_20ptr_3c_20t_20_3e_20_3e_905',['isPtr&lt; Ptr&lt; T &gt; &gt;',['../structtgbotxx_1_1is_ptr_3_01_ptr_3_01_t_01_4_01_4.html',1,'tgbotxx']]],
  ['isptr_3c_20ptrc_3c_20t_20_3e_20_3e_906',['isPtr&lt; PtrC&lt; T &gt; &gt;',['../structtgbotxx_1_1is_ptr_3_01_ptr_c_3_01_t_01_4_01_4.html',1,'tgbotxx']]]
];
