var searchData=
[
  ['callbackgame_617',['CallbackGame',['../structtgbotxx_1_1_callback_game.html',1,'tgbotxx']]],
  ['callbackquery_618',['CallbackQuery',['../structtgbotxx_1_1_callback_query.html',1,'tgbotxx']]],
  ['chat_619',['Chat',['../structtgbotxx_1_1_chat.html',1,'tgbotxx']]],
  ['chatadministratorrights_620',['ChatAdministratorRights',['../structtgbotxx_1_1_chat_administrator_rights.html',1,'tgbotxx']]],
  ['chatinvitelink_621',['ChatInviteLink',['../structtgbotxx_1_1_chat_invite_link.html',1,'tgbotxx']]],
  ['chatjoinrequest_622',['ChatJoinRequest',['../structtgbotxx_1_1_chat_join_request.html',1,'tgbotxx']]],
  ['chatlocation_623',['ChatLocation',['../structtgbotxx_1_1_chat_location.html',1,'tgbotxx']]],
  ['chatmember_624',['ChatMember',['../structtgbotxx_1_1_chat_member.html',1,'tgbotxx']]],
  ['chatmemberadministrator_625',['ChatMemberAdministrator',['../structtgbotxx_1_1_chat_member_administrator.html',1,'tgbotxx']]],
  ['chatmemberbanned_626',['ChatMemberBanned',['../structtgbotxx_1_1_chat_member_banned.html',1,'tgbotxx']]],
  ['chatmemberleft_627',['ChatMemberLeft',['../structtgbotxx_1_1_chat_member_left.html',1,'tgbotxx']]],
  ['chatmembermember_628',['ChatMemberMember',['../structtgbotxx_1_1_chat_member_member.html',1,'tgbotxx']]],
  ['chatmemberowner_629',['ChatMemberOwner',['../structtgbotxx_1_1_chat_member_owner.html',1,'tgbotxx']]],
  ['chatmemberrestricted_630',['ChatMemberRestricted',['../structtgbotxx_1_1_chat_member_restricted.html',1,'tgbotxx']]],
  ['chatmemberupdated_631',['ChatMemberUpdated',['../structtgbotxx_1_1_chat_member_updated.html',1,'tgbotxx']]],
  ['chatpermissions_632',['ChatPermissions',['../structtgbotxx_1_1_chat_permissions.html',1,'tgbotxx']]],
  ['chatphoto_633',['ChatPhoto',['../structtgbotxx_1_1_chat_photo.html',1,'tgbotxx']]],
  ['chatshared_634',['ChatShared',['../structtgbotxx_1_1_chat_shared.html',1,'tgbotxx']]],
  ['choseninlineresult_635',['ChosenInlineResult',['../structtgbotxx_1_1_chosen_inline_result.html',1,'tgbotxx']]],
  ['contact_636',['Contact',['../structtgbotxx_1_1_contact.html',1,'tgbotxx']]]
];
