name: build-windows

# build on pushes and pull requests on main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        architecture: [x64] #architecture: [x86, x64]
        build-platform: [x64] #build-platform: [Win32, x64]

    defaults:
      run:
        shell: cmd
     
    steps:
    # https://github.com/actions/checkout
    - uses: actions/checkout@v4


    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2
      with: 
        vs-version: '16.8' # using vs 16.8.3 in my local machine Help -> About Microsoft Visual Studio


    - name: Generate Project Files & Build Solution
      run: |
        md cmake-build-debug && cd cmake-build-debug
        cmake .. -G"Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=Debug -DENABLE_TESTS=ON
        msbuild tgbotxx.sln -property:Configuration=Release,MultiProcessorCompilation=true -maxCpuCount -verbosity:minimal -noLogo

