name: build-ubuntu

# build on pushes and pull requests on main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  TESTS_BOT_TOKEN: ${{ secrets.TESTS_BOT_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [x64] #architecture: [x86, x64]
        build-platform: [x64] #build-platform: [x86, x64]

    steps:
    # https://github.com/actions/checkout
    - uses: actions/checkout@v4

    - name: Update apt repositories & install deps
      run: |
        sudo apt update
        sudo apt-get install cmake g++ make ninja-build libssl-dev

    - name: Ensure deps are installed
      run: |
        cmake --version
        g++ --version
        make --version
        ninja --version

    - name: Build & run CText flow
      run: |
        mkdir cmake-build-debug && cd cmake-build-debug
        cmake .. -GNinja -DCMAKE_BUILD_TYPE=Debug -DENABLE_TESTS=ON
        export TESTS_BOT_TOKEN=${{ secrets.TESTS_BOT_TOKEN }}
        ninja tests/all -j$(nproc)
        ninja test
