name: build-ubuntu

# build on pushs and pull requests on main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [x64] #architecture: [x86, x64]
        build-platform: [x64] #build-platform: [x86, x64]

    steps:
    # https://github.com/actions/checkout
    - uses: actions/checkout@v4

    - name: Update apt repositories & install deps
      run: |
        sudo apt update
        sudo apt-get install cmake g++ make ninja-build libssl-dev valgrind

    - name: Generate ninja files
      run: |
        mkdir cmake-build-debug && cd cmake-build-debug
        cmake .. -GNinja -DCMAKE_BUILD_TYPE=Debug -DENABLE_TESTS=ON
    
    - name: Make tests
      run: ninja tests/all -j$(nproc)
    
    - name: Export TESTS_BOT_TOKEN to env
      run: export TESTS_BOT_TOKEN=${{ secrets.TESTS_BOT_TOKEN }}
      
    - name: Run CTest flow
      run: ninja test
