name: build-windows

# build on pushes and pull requests on main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        architecture: [x64] #architecture: [x86, x64]
        build-platform: [x64] #build-platform: [Win32, x64]

    defaults:
      run:
        shell: cmd
     
    steps:
    # https://github.com/actions/checkout
    - uses: actions/checkout@v4

    - name: Ensure deps are installed
      run: |
        cmake --version
        make --version
        ninja --version

    - name: Generate Project Files & Build Solution
      run: |
        md cmake-build-debug && cd cmake-build-debug
        cmake .. -GNinja -DCMAKE_BUILD_TYPE=Debug -DENABLE_TESTS=ON
        ninja tests/all
        ninja test
        
